#!/usr/bin/python


# === Instructions ===

# You are going to write a program which will select a random name from a list of (comma-separated) names. The person selected will have to pay for everybody's food bill.

# Important: You are not allowed to use the choice() function.



# Split string method
names_string = input("Give me everybody's names, separated by a comma. ")
names = names_string.split(", ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
import random

last_idx = len(names) - 1
rand_idx = random.randint(0, last_idx)
print(f"{names[rand_idx]} is going to buy the meal today!")

